# Generated by Django 3.0.1 on 2020-01-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
