# Generated by Django 3.0.1 on 2020-02-02 19:13

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200117_1137'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
